MSRM.Capstone/MSRM.Capstone.UI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MSRM.Capstone.BLL;
using MSRM.Capstone.Model;
using MSRM.Capstone.UI.Models;

namespace MSRM.Capstone.UI.Controllers
{
    public class AdminController : Controller
	{
        // GET: Admin
        [Authorize(Roles = "SuperUser, User")]
        public ActionResult Index()
		{
            if (User.IsInRole("User"))
            {
                return RedirectToAction("PostManagement");
            }
            else
            {
                return View();
            }
		}

        [Authorize(Roles = "SuperUser")]
        public ActionResult UserManagement()
		{
			return View();
		}

        [Authorize(Roles = "SuperUser")]
        public ActionResult ManagePages()
		{
			List<StaticPage> pages = new List<StaticPage>();

			StaticPage p = new StaticPage();
			p.StaticPageTitle = "TestPage";
			
			pages.Add(p);

			return View(pages);
		}

   
        [HttpPost]
		public ActionResult CreateStaticPage(StaticPage staticPage)
		{
			var pages = new StaticPagesManager();
			var response = pages.CreateStaticPage(staticPage);

			//if (response.Success)
			//{
			//    return View();
			//}

			return View();
		}

        [Authorize(Roles = "SuperUser")]
        public ActionResult CreateStaticPage()
		{
			return View();
		}

        [Authorize(Roles = "SuperUser")]
        public ActionResult EditPage()
		{
				return View();
		}

        [Authorize(Roles = "SuperUser, User")]
        public ActionResult PostManagement()
		{
			return View();
		}
	}
}

MSRM.Capstone/MSRM.Capstone.UI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MSRM.Capstone.UI.Controllers
{
    [Authorize(Roles = "SuperUser")]
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }
    }
}

MSRM.Capstone/MSRM.Capstone.UI/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace MSRM.Capstone.UI.Controllers
{
    public class MessageController : Controller
    {
        [Authorize(Roles = "SuperUser")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SendMessage()
        {
            return View();
        }

    }
}

MSRM.Capstone/MSRM.Capstone.UI/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MSRM.Capstone.BLL;
using MSRM.Capstone.Model;

namespace MSRM.Capstone.UI.Controllers
{
    [Authorize(Roles = "SuperUser")]
    public class TagController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MSRM.Capstone/MSRM.Capstone.UI/Views/Admin/CreateStaticPage.cshtml
@using System.ServiceModel.Configuration
@using System.Web.UI.WebControls
@model MSRM.Capstone.Model.StaticPage

@{
    ViewBag.Title = "Create Static Page";
}

<h2>Create Static Page</h2>


<div class="form-horizontal">
    <a class="btn btn-primary btn-sm" href="/Admin/ManagePages" role="button">Return to Manage Pages</a>
    @using (Html.BeginForm("CreateStaticPage", "Admin"))
    {
        <div class="form-group">
            <div class="col-md-12">
                <input type="text" name="StaticPageTitle" class="form-control" value="Enter Page Title"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <p class="enter-content">Enter Page Content Below</p>
                <textarea id="pageText"></textarea>
                <input id="StaticPageContent" name="StaticPageContent" type="hidden" value="" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3">
                <input id="btnSubmit" type="submit" value="Publish"/>
            </div>
        </div>
    }
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            tinyMCE.triggerSave();
            $('#btnSubmit').click(function () {
                var inputs = tinyMCE.get('pageText').getContent();
                $('#StaticPageContent').val(inputs);
            });
        });
    </script>
    }

MSRM.Capstone/MSRM.Capstone.UI/Views/Admin/EditPage.cshtml
@model MSRM.Capstone.Model.StaticPage

@{
    ViewBag.Title = "EditPage";
}

<h2>EditPage</h2>

MSRM.Capstone/MSRM.Capstone.UI/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin_Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div align="center">
    <h2>Administrator Menu</h2>
</div>

<br/>

<div align="center">
    @Html.ActionLink("Manage Tags", "Index", "Tag", null, new {@class = "btn btn-primary btn-lg btn-block" })
    <br/>
    @Html.ActionLink("Manage Categories", "Index", "Category", null, new {@class = "btn btn-primary btn-lg btn-block" })
    <br/>
    @Html.ActionLink("Manage Users", "UserManagement", "Admin", null, new { @class = "btn btn-primary btn-lg btn-block" })
    <br />
    @Html.ActionLink("Manage Posts", "PostManagement", "Admin", null, new { @class = "btn btn-primary btn-lg btn-block" })  @*Just pointing to Default Manage Page, needs implementation.*@
    <br/>
    @Html.ActionLink("Manage Pages", "ManagePages", "Admin", null, new { @class = "btn btn-primary btn-lg btn-block" })  @*Just pointing to Default Manage Page, needs implementation.*@
    <br/>
    @Html.ActionLink("Messages", "Index", "Message", null, new { @class = "btn btn-primary btn-lg btn-block" }) 
    <br />
    @Html.ActionLink("Back to Home Page", "Index", "Home", null, new {@class = "btn btn-danger btn-lg btn-block"})
    <br/>
</div>

MSRM.Capstone/MSRM.Capstone.UI/Views/Admin/ManagePages.cshtml
@model List<MSRM.Capstone.Model.StaticPage>

@{
    ViewBag.Title = "ManagePages";
}

<h2>Manage Pages</h2>

<div class="page-title-list">
    <a class="btn btn-primary btn-sm" href="/Admin/CreateStaticPage" role="button">Create New Page</a>
    <table id="titles" class="table table-striped page-title-list">
        @*<thead>
            <tr>
                <th>Page ID</th>
                <th>Page Title</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td>About</td>
                <td>
                    <button class="btn btn-danger btn-sm">DELETE</button>
                </td>
            </tr>
            </tbody>*@
    </table>
</div>

@section scripts{

    <script>
        var uri = '/api/StaticPages/';

        $(document).ready(function () {
            GetPageHeadersForTable();

            $(document).on("click", '#Delete', function (e) {
                e.preventDefault();
                var link = $(this);
                var staticPageId = $(link).attr("name");
                DeletePage(staticPageId);
            });

            //$(document).on("click", '#Edit', EditPage);

        });

        function GetPageHeadersForTable() {
            $.getJSON(uri + 'GetPageHeaders').done(function (data) {
                $('#titles').empty();
                $(recreateTableHead()).appendTo($('#titles'));
                $.each(data, function (index, titles) {
                    $(createRow(titles)).appendTo($('#titles'));
                });
                $(recreateCLoseTableBody()).appendTo($('#titles'));
            });
        };

        function recreateTableHead() {
            return '<thead><tr><th>Page ID</th><th>Page Title</th><th>Action</th></thead><tbody></tr>';
        }

        function createRow(row) {
            console.log(row);
            return '<tr><td>' + row.StaticPageId + '</td><td>' + row.StaticPageTitle + '</td>' +
                '<td>' +
                '<a id="Delete" name="' + row.StaticPageId + '" class="btn btn-danger btn-sm" href="#/" role="button">Delete</a></td>';
        };

        //<a id="Edit" class="btn btn-warning btn-sm" href="#/' + row.StaticPageId + '" role="button">Edit</a> 
        function recreateCLoseTableBody() {
            return '</tbody>';
        }

        function DeletePage(id) {
            $.ajax({
                url: '/api/StaticPages/Delete/' + id,
                type: 'DELETE',
                success: function () {
                    window.location.href = "/Admin/ManagePages";
                },
                error: function (xhr, status, err) {
                    alert('error: ' + err);
                }
            });
        }

    </script>
}



@*@foreach (var page in Model)
    {
        <label>Title:</label>

        <br/>

        <p>@Html.DisplayFor(m => page.StaticPageTitle)</p>
        <p>@Html.ActionLink("Edit Page", "EditPage", "Admin")</p>
        <button class="btn btn-danger">Delete Page</button>
    }*@

MSRM.Capstone/MSRM.Capstone.UI/Views/Admin/PostManagement.cshtml
@{
    ViewBag.Title = "PostManagement";
}

<h4>Post Management</h4>

<div class="main">

    <div class="row">
        <div id="errormsg"></div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            @if (Request.IsAuthenticated && (User.IsInRole("SuperUser")))
            {
                <select class="form-control selections">
                    <option value="1">Draft</option>
                    <option value="2">Review</option>
                    <option value="3">Decline</option>
                    <option value="4">Published</option>
                </select>
            }
            else if (Request.IsAuthenticated && (User.IsInRole("User")))
            {
                <select class="form-control selections">
                    <option value="1">Draft</option>
                    <option value="2">Review</option>
                    <option value="3">Decline</option>
                </select>
            }
        </div>
    </div>
    <div class="row">
        <div id="posts" class="col-md-12">
            <div id="post-postId" class="post-postId">
                <div class="post-teaser">
                    <div class="post-header">
                        <h1>Title</h1>
                        <p>
                            Sarah | <span class="date-string">Date</span>
                            <span><button class="btn btn-warning post-teaser-btn pull-right">Open</button></span>
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <ul class="pager">
                <li class="previous" id="new"><a href="#">&larr; Newer</a></li>
                <li class="next" id="old"><a href="#">Older &rarr;</a></li>
            </ul>
        </div>
    </div>
</div>
@Html.Partial("_SinglePostModel")
@section scripts{
    <script>
        var postUri = '/api/posts/';

        var pageNum = 1;
        var totalPostNum;
        var maxPage;

        var data = {
            id: 1,
            size: 10,
            status: $('.selections').val()
        };

        $(document).ready(function() {
            getAllPosts(data);
            $('.selections').change(function () {
                data.status = $('.selections').val();
                getAllPosts(data);
            });
            $('#submitChanges').click(function() {
                updatePost();
                $('#singlePost').modal('hide');
            });
            $('#singlePost').change(function() {
                $('#submitChanges').prop('disabled', false);
            });

            $('#old').click(function () {
                if (maxPage != pageNum) {
                    pageNum++;
                    data.id = pageNum;
                    getAllPosts(data);
                }
            });
            $('#new').click(function () {
                if (pageNum > 1) {
                    pageNum--;
                    data.id = pageNum;
                    getAllPosts(data);
                }

            });
            
        });
        
        function getSinglePosts(id) {
            $("#categoryModal").tagit("removeAll");
            $("#tagModal").tagit("removeAll");
            $('#submitChanges').prop('disabled', true);
            $('#singlePost').modal('show');
            $.getJSON(postUri + 'GetSinglePost/' + id).done(function(data) {
                $('#postId').val(id);
                $('#headingModal').val(data.Title);
                $('#categoryModal').val(getList(data.Categories));

                $('#tagModal').val(getTagList(data.Tags));
                tinyMCE.activeEditor.setContent(data.Posting);
                $('#rad' + data.StatusId).prop('checked', true);
                if (data.StatusId == 3) {
                    $('#rad' + 2).prop('checked', true);
                }
            });
        };

        function getList(item) {

            var itemList = "";
            for (var i = 0; i < item.length; i++) {
                $("#categoryModal").tagit("createTag", item[i].CategoryName);
                itemList += item[i].CategoryName;
                if (i != item.length - 1) {
                    itemList += ',';
                }
            };
            return itemList;
        }

        function getTagList(item) {

            var itemList = "";
            for (var i = 0; i < item.length; i++) {
                $("#tagModal").tagit("createTag", item[i].Name);
                itemList += item[i].Name;
                if (i != item.length - 1) {
                    itemList += ',';
                }
            };
            return itemList;
        }

        function getAllPosts(data) {
            $.getJSON(postUri + 'get/', data).done(function(data) {
                $('#posts').empty();
                totalPostNum = data.Total;
                maxPage = Math.floor(totalPostNum / 10);
                if (totalPostNum % 10 > 0) {
                    maxPage++;
                }
                $.each(data.Posts, function(index, post) {
                    $(createDiv(post)).appendTo($('#posts'));
                });
            });
        };

        function updatePost() {
            var updatedPost = {};
            var post = {};
            updatedPost.post = post;

            updatedPost.post.PostId = $('#postId').val();
            updatedPost.post.Title = $('#headingModal').val();
            updatedPost.post.Posting = tinyMCE.get('postModal').getContent();
            updatedPost.post.StatusId = $('input[name="status"]:checked').val();
            updatedPost.CategoryString = $('#categoryModal').val();
            updatedPost.TagString = $('#tagModal').val();

            $.post(postUri + 'Update/', updatedPost).done(function() {
                    getAllPosts(data);
                })
                .fail(function(jqXhr, status, error) {
                    //$(errorMessage(error)).appendTo($('#errormsg'));
                });
        }

        function createDiv(post) {
            return '<div class="blog-posts"><div id="post-' + post.PostId + '" class="post-' + post.PostId + '">' +
                '<div class="post-teaser"><div class="post-header"><h1>' + post.Title + '</h1>' +
                '<p><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span class="sarah">Sarah</span> ' +
                '<span class="glyphicon glyphicon-time" aria-hidden="true"></span> <span class="date-string">' + post.DateString +
                '</span>  <span><button id="btnModal" onClick="getSinglePosts(' + post.PostId + ')" "data-toggle="modal" data-target="#singlePost" class="btn btn-warning btn-xs post-teaser-btn pull-right">Open</button></span></p></div></div>';
        };

        $("#tagModal").tagit({
            placeholderText: "Tags",
            allowSpaces: true

        });
        $("#categoryModal").tagit({
            placeholderText: "Categories",
            allowSpaces: true
        });
    </script>
}

MSRM.Capstone/MSRM.Capstone.UI/Views/Admin/UserManagement.cshtml
@{
    ViewBag.Title = "User Management Menu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align="center">
    <h2>User Menu</h2>
</div>

<br />


<form>
    <select id="users">
        <option></option>
    </select>
    <div id="userinfo">

    </div>
    <br><br>
</form>

<p>
    @Html.ActionLink("Register a new user", "Register", "Account")
</p>

<div class="col-lg-6 col-lg-offset-3" style="padding-bottom: 1em">
    @Html.ActionLink("Return to Admin Page", "Index", "Admin", null, new { @class = "btn btn-info btn-block" })
</div>

@section Scripts
{
    <script>
        var userUri = '/api/Users/';

        $(document).ready(function () {
            loadUsers();
        });

        $(function () {
            $("#users").change(function () {
                $.getJSON(userUri + "GET/")
                    .done(function (data) {
                        $('#test div').remove();
                        $.each(data, function (index, user) {
                            if ($("#users").val() === user.UserEmail) {
                                $("<div></br>User Name: <input value=" + user.UserName + " id=\"UserName\"><br>" +
                                    "<input type=\"hidden\" value=" + user.UserEmail + " id=\"UserEmail\"><br>" +
                                    "<input type=\"radio\" name=\"role\" value=\"1\" id=\"1\"> Super User<br>" +
                                "<input type=\"radio\" name=\"role\" value=\"2\" id=\"2\"> User<br>" +
                                "<input type=\"radio\" name=\"role\" value=\"3\" id=\"3\"> Disabled<br>" +
                                "<button type=\"button\" id=\"btnEditUser\" class=\"btn btn-success btn-block\">Edit User</button></div>").appendTo($('#userinfo'));
                                $('#' + user.RoleId).prop('checked', true);
                            }
                        });
                    });
            });
        });

        function loadUsers() {
            $.getJSON(userUri + "GET/")
                .done(function (data) {

                    $.each(data, function (index, user) {
                        $("<option value=" + user.UserEmail + ">" + user.UserEmail + "</option>").appendTo($('#users'));
                    });
                });
        };

        $(document).on("click", "#btnEditUser", function () {
            var user = {};

            user.UserName = $("#UserName").val();
            user.UserEmail = $("#UserEmail").val();
            user.RoleId = $("input[name=role]:checked").val();

            $.post(userUri + "POST/", user)
                .done(function () {
                    location.reload();
                })
                .fail(function (jqXhr, status, err) {
                    $("#errorMsg").appendTo("<div class=\"col-xs-offset-1 col-xs-10 alert alert-danger\"><a href=\"#\" class=\"close\" data-dismiss=\"alert\">&times;</a>" + err + "</div>");
                    location.reload();
                });
        });
    </script>
}